@echo off
echo Starting STT server...
start cmd /k "venv\Scripts\python.exe stt_server.py"
echo Starting TTS server...
start cmd /k "venv\Scripts\python.exe tts_server.py"
echo Starting Embeddings server...
start cmd /k "venv\Scripts\python.exe embeddings_server.py"
